# Generated by Django 4.2.2 on 2023-06-17 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.UUIDField(default=uuid.UUID('9a08c049-538f-41e5-9af4-46aa239af2c6'), primary_key=True, serialize=False)),
                ('nombre_plato', models.TextField(max_length=15, unique=True)),
                ('precio_plato', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('stock_plato', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('activado', models.BooleanField(default=True)),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.UUIDField(default=uuid.UUID('fc7c05bd-5dbb-43e7-a348-55523a715845'), primary_key=True, serialize=False)),
                ('sub_total', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('domicilio', models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)])),
                ('finalizado', models.BooleanField(default=False)),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.plato')),
            ],
        ),
    ]
