# Generated by Django 4.2.2 on 2023-06-25 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.CharField(default='Sin imagen', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('c75e0bc7-8669-4d7f-846b-c9a824a58de4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('9e152033-6741-4c63-b15a-995301b1b598'), primary_key=True, serialize=False),
        ),
    ]
