# Generated by Django 4.2.2 on 2023-07-05 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('9f99b750-18cd-425f-a8ea-b8a3d55df115'), primary_key=True, serialize=False),
        ),
    ]
