# Generated by Django 4.2.2 on 2023-06-16 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('faa4b905-195d-4918-b336-1abbb6242e2a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('3bb0542d-512e-4357-ac86-29e254298642'), primary_key=True, serialize=False),
        ),
    ]
