# Generated by Django 4.2.2 on 2023-06-25 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_plato_imagen_alter_carrito_id_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('5844fec3-ae76-4faf-abb7-3002d09266fd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('9a84e817-c515-447e-9496-cfc347e056f0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.CharField(default='Sin imagen', max_length=500, unique=True),
        ),
    ]
