# Generated by Django 4.2.2 on 2023-06-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ingrediente_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_ing',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
