# Generated by Django 4.2.2 on 2023-07-05 02:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_carritocompras_id_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('53c448ff-70ca-45ee-bf83-8ddc71b98f0d'), primary_key=True, serialize=False),
        ),
    ]
