# Generated by Django 4.2.1 on 2023-06-17 22:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_carrito_id_carrito_alter_plato_id_plato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[a-z  A-Z]*$', 'Ingrese solo letras')])),
                ('apellido', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[a-z  A-Z]*$', 'Ingrese solo letras')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('16360114-29ff-48df-85bd-fefcaf5709f6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('17a0a914-89f3-4c5b-a342-db109dbbb296'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.TextField(max_length=15, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999), django.core.validators.RegexValidator('^[a-z  A-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
