# Generated by Django 4.2.2 on 2023-06-19 21:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cliente_alter_carrito_id_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('402b551f-8da0-4247-bb17-c9b075cb25e8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('3d6a2de6-a8d5-4369-ae5c-5c5edf4d48b0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('^[a-z  A-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
