# Generated by Django 4.2.2 on 2023-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ingrediente_id_ing_alter_plato_id_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_ing',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
