# Generated by Django 4.2.1 on 2023-07-07 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_carritocompras_id_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('a17e68e9-20b3-4e9c-81f5-c2f5807fc87f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.CharField(default='Sin imagen', max_length=10000, unique=True),
        ),
    ]
