# Generated by Django 4.2.2 on 2023-06-19 21:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_carrito_id_carrito_alter_plato_id_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('a23b235e-9a39-496c-9d8c-4e2f4b34a95f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[a-z\\\\sA-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[a-z\\\\sA-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('437c1283-5d39-4ccc-a4aa-f1370aea978d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('^[a-z\\\\sA-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
