# Generated by Django 4.2.1 on 2023-07-07 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_carritocompras_id_carrito_alter_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='id_carrito',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
