# Generated by Django 4.2.2 on 2023-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ingrediente_id_ing_alter_plato_id_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_ing',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
