# Generated by Django 4.2.2 on 2023-06-19 21:59

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_carrito_id_carrito_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('848447c5-c528-4727-a830-0dcf2c84f83d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Ingrese solo letras')]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('820f8c37-4b0f-452c-9786-438dd5dda6fe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
