# Generated by Django 4.2.2 on 2023-06-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ingrediente_id_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_ing',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
