# Generated by Django 4.2.2 on 2023-06-19 22:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_carrito_id_carrito_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('e916a5ce-d1d4-4bb9-ba82-a77a90ac4ade'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('aa19b292-8eca-4d09-9059-b9b1749d6c58'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.TextField(unique=True, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
