# Generated by Django 4.2.2 on 2023-06-13 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_ingrediente_id_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_ing',
            field=models.UUIDField(default=uuid.UUID, primary_key=True, serialize=False),
        ),
    ]
