# Generated by Django 4.2.2 on 2023-06-19 22:15

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_carrito_id_carrito_alter_plato_id_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('63f92b4d-e666-4475-948f-80f249edff3b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('fc4cd840-411b-4e1d-a2f6-d5c2a728e90b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
