# Generated by Django 4.2.1 on 2023-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_ingrediente_id_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.TextField(max_length=15),
        ),
    ]
