# Generated by Django 4.2.2 on 2023-06-19 22:22

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_carrito_id_carrito_alter_plato_id_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('594c7306-79a1-4e6e-8cfc-aefc55b44edb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('c73b7468-c56e-4a1a-9387-a2a797f582e0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z A-Z]*$', 'Ingrese solo letras')]),
        ),
    ]
