# Generated by Django 4.2.2 on 2023-06-14 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_ingrediente_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_ing',
            field=models.UUIDField(default=uuid.UUID('ce09d6d5-9158-41a5-aab6-cdf66a69a913'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('2575d376-21bc-4856-ac7d-2db41705e462'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DetallePlato',
            fields=[
                ('id_dPlato', models.UUIDField(default=uuid.UUID('b589f209-05ba-4207-b411-19e148279c7e'), primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.ingrediente')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.plato')),
            ],
        ),
    ]
