# Generated by Django 4.2.2 on 2023-06-19 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_carrito_id_carrito_alter_plato_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('26622b09-505b-42c6-bad3-0eca4378c036'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('e376f786-e196-46b2-8a4f-31830ede861d'), primary_key=True, serialize=False),
        ),
    ]
