# Generated by Django 4.2.2 on 2023-06-19 22:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_carrito_id_carrito_alter_plato_id_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='domicilio',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('347ac948-1d0f-4fb9-8e9f-31d0fb061f45'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('d07d5b64-fee1-4334-8013-8c7c558242e4'), primary_key=True, serialize=False),
        ),
    ]
