# Generated by Django 4.2.2 on 2023-06-20 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_carrito_finalizado_alter_carrito_id_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='activado',
        ),
        migrations.AddField(
            model_name='plato',
            name='finalizado',
            field=models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITAD', 'DESHABILITADO')], default='HABILITADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='finalizado',
            field=models.CharField(choices=[('FINALIZADO', 'FINALIZADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('e6dd2ae0-87ba-40bb-bbe2-d739a7f3e2ca'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('c996def3-59df-4b87-9519-63c652b9ef96'), primary_key=True, serialize=False),
        ),
    ]
