# Generated by Django 4.2.2 on 2023-06-20 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_finalizado_plato_estado_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.UUIDField(default=uuid.UUID('dbba7b34-585a-4ecb-9c63-1d48f8c7f68d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.UUIDField(default=uuid.UUID('9539c359-58bb-46fa-bf62-92c40c8eedc7'), primary_key=True, serialize=False),
        ),
    ]
